### ISSUE TITLE
不能自动抢红包,能防撤回消息，但是不会提示该消息是否已撤回

### ISSUE THREAD

**Issue by LiHang941** [qssq/feedback#1]
已经安装了加密库
打开qq的时候经常无响应

![image](https://gitee.com/lh1329/images/raw/master/qssq/1.jpg)

![image](https://gitee.com/lh1329/images/raw/master/qssq/3.jpg)

![image](https://gitee.com/lh1329/images/raw/master/qssq/2.jpg)

**Comment by qssq** [comment]
1、打开q++界面 截图 方便看 q++是什么环境
2、打开qq关于方便看 QQ版本号
3、打开QQ设置->Q++->j兼容性截图查看是否有错误信息。

**Comment by LiHang941** [comment]
华为机器。。git自动切图，佛了

**Comment by LiHang941** [comment]
图片地址 
https://gitee.com/lh1329/images/raw/master/qssq/1.jpg

https://gitee.com/lh1329/images/raw/master/qssq/3.jpg

https://gitee.com/lh1329/images/raw/master/qssq/2.jpg

**Comment by qssq** [comment]
q++软件的图呢,你到底是 啥环境，你试试q++1.0.7吧

**Comment by LiHang941** [comment]
好的，我先试试新版本，这个问题有点时间了
