### ISSUE TITLE
您好，qssq技术大大

### ISSUE THREAD

**Issue by my77game** [qssq/feedback#21]
我看您有做了一个
V++模块 微信机器人、微信抢红包 的插件

我们想要做一个微信跟qq都可以使用的xposed插件

不知道您有没时间详聊一下。愿不愿意开发

**Comment by qssq** [comment]
juti

**Comment by my77game** [comment]
juti 不懂@@

qssq大大 ??

方便加一下 QQ MAIL吗
my77game@qq.com
