### ISSUE TITLE
v＋＋不显示

### ISSUE THREAD

**Issue by zfq0421** [qssq/feedback#33]
![Screenshot_20190526-012100](https://user-images.githubusercontent.com/51030075/58372841-8235f500-7f56-11e9-89df-347a9bbb1b13.jpg)
![Screenshot_20190526-012106](https://user-images.githubusercontent.com/51030075/58372842-82ce8b80-7f56-11e9-82aa-995101745bff.jpg)

**Comment by qssq** [comment]
只支持7.0.3
