### ISSUE TITLE
Q++入口消失 v8.0.5

### ISSUE THREAD

**Issue by Carrey904** [qssq/feedback#34]
**一加6T**

**QQ版本`8.0.5`**  

**Q++版本`1.3.2`**

**更新前还好好的，更新后就没了**  

![Screenshot_20190603-1919407d031.jpg](https://miao.su/images/2019/06/03/Screenshot_20190603-1919407d031.jpg)  
![Screenshot_20190603-192051bb22b.jpg](https://miao.su/images/2019/06/03/Screenshot_20190603-192051bb22b.jpg)  
![Screenshot_20190603-192911834a7.jpg](https://miao.su/images/2019/06/03/Screenshot_20190603-192911834a7.jpg)

**Comment by qssq** [comment]
更新q++
