### ISSUE TITLE
如果能在app分身多开里使用就好了

### ISSUE THREAD

**Issue by kpwd** [qssq/feedback#4]
应该是可以实现的吧，亲测微x模块可以在“双开助手”里使用。

**Comment by kpwd** [comment]
如果技术实现太困难就算啦，我也编写过安卓程序，理解这个感觉

**Comment by qssq** [comment]
我做了加密处理，防止代码窃取，自然会导致出现一些兼容性问题，如果正常情况能使用我一般不会处理，除非自己本身需要，再说了这东西没钱谁干？ 我能坚持也无非是自己需要罢了。

**Comment by qssq** [comment]
现在已经兼容分身大师X版本了，多开？哪个软件

**Comment by kpwd** [comment]
双开助手

2018年10月20日 09:56于 情随事迁 <notifications@github.com>写道：

现在已经兼容分身大师X版本了，多开？哪个软件

**Comment by kpwd** [comment]
建议可以自定义包名，这样理论上支持所有的多开软件

2018年10月20日 09:56于 情随事迁 <notifications@github.com>写道：

现在已经兼容分身大师X版本了，多开？哪个软件
