### ISSUE TITLE
使用sdk开发 调用api.sendPicMsg 没有问题  api.sendMsg 也可以但是 sendPicAndTextMsg没有任何反应  sdk 版本2.7 机器人版本3.0.1

### ISSUE THREAD

**Issue by John-jin** [qssq/feedback#47]
**症状**
描述一下出了什么问题，越详细越能快速定位是什么问题

**Q++界面截图**
打开Q++软件截图即可

**QQ版本号和版本vode**
如果激活的情况下可以打开QQ->关于把QQ版本号截图过来 也行
**手机型号和版本号 Api**
**崩溃错误信息**
如果Qq设置能出现入口，那么点击入口进去->兼容性，把错误信息截图发到这里。
**说明**
需要手机型号 api版本号
需要QQ版本号
需要Q++版本号
需要错误日志

**Comment by John-jin** [comment]
getControlApi().sendPicMsg(item, item.getFrienduin(), item.getSenderuin(), picPath);
getControlApi().sendMsg(item.setMessage("发送文字"));           getControlApi().sendPicAndTextMsg(item,item.getFrienduin(),item.getSenderuin(),picPath,"这是图文消息");

**Comment by qssq** [comment]
暂不支持
