### ISSUE TITLE
口令红包bug反馈

### ISSUE THREAD

**Issue by AmalwayshereU** [qssq/feedback#5]
**症状**
口令红包不发送口令直接就抢了，口令红包设置正常，我选择了“抢红包要发口令
![gy hw v m ghm j63 t](https://user-images.githubusercontent.com/25956759/47058513-f86fbd80-d1f7-11e8-94f2-778b8a583e58.png)
![s12 8b5v ua v dg3zar7i8](https://user-images.githubusercontent.com/25956759/47058514-f86fbd80-d1f7-11e8-8389-d492e2997281.png)

”

**Comment by qssq** [comment]
是否属于 不发口令的违禁词之类，比如默认添加了爸,妈,微信,各种，如果是这些词是不会发口令的。
