### ISSUE TITLE
未root太极框架下闪照还是会消失

### ISSUE THREAD

**Issue by adelacvg** [qssq/feedback#53]
**症状**
没有root，太极框架下闪照还是会消失

**Q++界面截图**
![Screenshot_20191010_140806_cn qssq666 q plus](https://user-images.githubusercontent.com/27419496/66543233-6dee3f80-eb67-11e9-9125-7c885a6463b8.png)

**QQ版本号和版本vode**
![image](https://user-images.githubusercontent.com/27419496/66542908-6c704780-eb66-11e9-957b-d5c37662833d.png)
**手机型号和版本号 Api**
![Screenshot_20191010_140620_com android settings](https://user-images.githubusercontent.com/27419496/66543200-4eefad80-eb67-11e9-9eb7-f20698b4c65c.png)

**崩溃错误信息**
![Screenshot_20191010_141435_com tencent mobileqq](https://user-images.githubusercontent.com/27419496/66543600-6c714700-eb68-11e9-8179-0bde4994c399.jpg)

**Comment by qssq** [comment]
更新适配
