### ISSUE TITLE
QQ8.15版本功能完全失效

### ISSUE THREAD

**Issue by DeepFeeling-1999** [qssq/feedback#55]
**症状**
QQ8.15版本功能完全失效，QQ设置能显示，Q++页面显示激活，但功能完全失效

**Q++界面截图**
![image](https://user-images.githubusercontent.com/44224016/70375597-539fca80-193a-11ea-9520-b4cd9f6b225e.png)

**QQ版本号和版本vode**
![R 97D5$L3$S2}{$TKZD 6(Q](https://user-images.githubusercontent.com/44224016/70375601-6adeb800-193a-11ea-89fd-d59b1f75daaf.jpg)

**手机型号和版本号 Api**
一加五，安卓9.0

**崩溃错误信息**
![B0C442B8CF6E9A3102DBEB6B540CA640](https://user-images.githubusercontent.com/44224016/70375611-7fbb4b80-193a-11ea-975f-b91d8c90063b.jpg)
![3C0A4ACA4346402818E9488E5241D06A](https://user-images.githubusercontent.com/44224016/70375612-847fff80-193a-11ea-94a2-8ba1c4b5e4d9.jpg)

**说明**
需要手机型号 api版本号
一加5
需要QQ版本号
8.15
需要Q++版本号
1.38
需要错误日志

**Comment by qssq** [comment]
不再更新
