### ISSUE TITLE
v++微信不能使用

### ISSUE THREAD

**Issue by zhangyining215** [qssq/feedback#56]
![Screenshot_2019-12-30-11-38-49](https://user-images.githubusercontent.com/39961193/71567544-d9a6cf80-2afa-11ea-8a0e-204f05e2de1b.png)
![Screenshot_2019-12-30-11-37-51](https://user-images.githubusercontent.com/39961193/71567546-dd3a5680-2afa-11ea-834f-b10d45dae20d.png)
![Screenshot_2019-12-30-11-37-23](https://user-images.githubusercontent.com/39961193/71567547-df9cb080-2afa-11ea-975f-57e5899350f2.png)
微信版本为7.09

**Comment by qssq** [comment]
不再更新
