### ISSUE TITLE
V++与chrome的兼容问题

### ISSUE THREAD

**Issue by Lorie-Scarlet** [qssq/feedback#60]
设备：Pixel2xl  android10（QQ1A.200205.002）
相关 Edxposed v4.5.4
          Magisk ce7b1ee（20306）

目前已经确认是V++导致chrome闪退
打开chrome可以维持1-2秒，然后直接退出
尝试过重装chrome及V++，系统也重新刷过
尝试过xposed的兼容模式
只要一关闭V++并重启问题就消失
其它浏览器没有问题
# chrome的dev beta canary均有同样问题

**Comment by yangfan0507** [comment]
傀儡术没得最新版本嘛？（好南郭）

**Comment by yangfan0507** [comment]
阿西吧

**Comment by yangfan0507** [comment]
傀儡术打不开orz

**Comment by yangfan0507** [comment]
2020都没有看见你跟新啥了嘻嘻，（补上新年快乐）

**Comment by qssq** [comment]
坐牢了
