### ISSUE TITLE
你好定制功能

### ISSUE THREAD

**Issue by jinshaoZ** [qssq/feedback#61]
屏蔽单人红包

**Comment by qssq** [comment]
不敢 违法

**Comment by jinshaoZ** [comment]
老哥：你QQ现在是多少了！ 之前加的好像都不在线了！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qssq/feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月2日(星期天) 晚上11:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qssq/feedback] 你好定制功能 (#61)





 
不敢 违法

**Comment by qssq** [comment]
> 老哥：你QQ现在是多少了！ 之前加的好像都不在线了！！！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "qssq/feedback" ***@***.***&gt;; 发送时间:&nbsp;2021年5月2日(星期天) 晚上11:48 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [qssq/feedback] 你好定制功能 (#61) 不敢 违法 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

35068264
