### ISSUE TITLE
你好定制功能，q89251564

### ISSUE THREAD

**Issue by jinshaoZ** [qssq/feedback#62]
**症状**
描述一下出了什么问题，越详细越能快速定位是什么问题

**Q++界面截图**
打开Q++软件截图即可

**QQ版本号和版本vode**
如果激活的情况下可以打开QQ->关于把QQ版本号截图过来 也行
**手机型号和版本号 Api**
**崩溃错误信息**
如果Qq设置能出现入口，那么点击入口进去->兼容性，把错误信息截图发到这里。
**说明**
需要手机型号 api版本号
需要QQ版本号
需要Q++版本号
需要错误日志

**Comment by qssq** [comment]
不敢
