### ISSUE TITLE
不能适配最新版QQ

### ISSUE THREAD

**Issue by szgzs3059888276** [qssq/feedback#63]
**症状**
描述一下出了什么问题，越详细越能快速定位是什么问题

**Q++界面截图**
打开Q++软件截图即可

**QQ版本号和版本vode**
如果激活的情况下可以打开QQ->关于把QQ版本号截图过来 也行
**手机型号和版本号 Api**
**崩溃错误信息**
如果Qq设置能出现入口，那么点击入口进去->兼容性，把错误信息截图发到这里。
**说明**
需要手机型号 api版本号
需要QQ版本号
需要Q++版本号
需要错误日志

**Comment by szgzs3059888276** [comment]
不能适配最新版QQ

**Comment by hhhhhhbit** [comment]
![Screenshot_2021-03-12-11-19-36-955_com android settings](https://user-images.githubusercontent.com/80452835/110887272-9d026680-82af-11eb-90d7-8377fee47a80.jpg)
![Screenshot_2021-03-12-11-11-59-847_com tencent mobileqq](https://user-images.githubusercontent.com/80452835/110887291-a7246500-82af-11eb-9072-e394edc25b1a.jpg)
![Screenshot_2021-03-12-11-11-56-837_com tencent mobileqq](https://user-images.githubusercontent.com/80452835/110887294-aab7ec00-82af-11eb-9549-377581ed35d3.jpg)
![Screenshot_2021-03-12-11-11-46-072_com miui securitycenter](https://user-images.githubusercontent.com/80452835/110887297-ab508280-82af-11eb-855f-47bf4f04c508.jpg)
![Screenshot_2021-03-12-11-11-37-089_com tencent mobileqq](https://user-images.githubusercontent.com/80452835/110887299-ac81af80-82af-11eb-9c2d-09c0277e1493.jpg)
![Screenshot_2021-03-12-11-21-10-179_com baidu searchbox](https://user-images.githubusercontent.com/80452835/110887344-c0c5ac80-82af-11eb-8cda-b35cb0fa7d2a.jpg)

**Comment by hhhhhhbit** [comment]
就是没用啊有显示设置但是抢不了红包

**Comment by qssq** [comment]
我19年10月身陷囹圄,服务器早就过期了,域名都被别人买了,可千万别被骗了哈!
另外我不会再更新了,因为这也有可能使我二次坐牢
!

**Comment by qssq** [comment]
不再更新。
