### ISSUE TITLE
关于q++与情迁机器人的问题

### ISSUE THREAD

**Issue by hhhhhhbit** [qssq/feedback#64]
![Screenshot_2021-03-11-17-05-35-012_cn qssq666 robot](https://user-images.githubusercontent.com/80452835/110762771-c7ecac00-8216-11eb-8710-22a4486ea696.jpg)
![Screenshot_2021-03-11-17-04-52-826_com tencent mobileqq](https://user-images.githubusercontent.com/80452835/110762779-ca4f0600-8216-11eb-85e1-204624ccbde3.jpg)
++
![Screenshot_2021-03-11-17-04-49-854_com tencent mobileqq](https://user-images.githubusercontent.com/80452835/110762787-ccb16000-8216-11eb-8161-a48bdc9a2a01.jpg)++

**Comment by qssq** [comment]
我19年10月身陷囹圄,服务器早就过期了,域名都被别人买了,可千万别被骗了哈!

**Comment by qssq** [comment]
https://t.me/qssq666

**Comment by qssq** [comment]
不再更新。
