### ISSUE TITLE
能否详细说明一下HOOKUI|AnyAppHook逆向神器如何使用

### ISSUE THREAD

**Issue by lvzhenbo** [qssq/feedback#65]
仅通过介绍我无法知道这个工具的使用方式，能否详细说明一下

**Comment by rxzcums** [comment]
看着很牛逼，可是不明白怎么用

**Comment by qssq** [comment]
群文件有视频， ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月19日(星期六) 晚上9:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [qssq/feedback] 能否详细说明一下HOOKUI|AnyAppHook逆向神器如何使用 (#65)

**Comment by qssq** [comment]
看群里视频------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月19日(星期六) 晚上9:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [qssq/feedback] 能否详细说明一下HOOKUI|AnyAppHook逆向神器如何使用 (#65)

**Comment by Dhruv420** [comment]
Can we get a link to the tutorial videos , can't find it. A simple starting tutorial will be appreciated as I am unable to use the app.

**Comment by qssq** [comment]
@Dhruv420  QQ group753309838

**Comment by qssq** [comment]
> 看着很牛逼，可是不明白怎么用

主要是配合logcat 使用的，不需要编写代码来进行类的动态输入 或者不需要填写代码来分析触摸事件堆栈，分析点击事件堆栈等，这些都是在hook后通过logcat查看，还有一些则手机端玩的。

**Comment by qssq** [comment]
可以默认开启自动hook 字符串，避免启动之后某些字符串逃逸，所以在hookui界面也有很多勾选选项，这些勾选后启动就会默认启用。 比如字符串hook勾选，然后启动app,然后过滤HOOKUI日志就能看到很多字符串出现了

**Comment by qssq** [comment]
如果要打印字符串出现的堆栈信息，就需要填写关键字匹配。

**Comment by Dhruv420** [comment]
> @Dhruv420 QQ group753309838

QQ account creation is the issue I don't have a Chinese number , do you have the tutorials of some other platforms like Telegram

**Comment by qssq** [comment]
t.me/lojunX里面有一个频道，我有空会把视频发在里面。

**Comment by qssq** [comment]
lojunX里面有一个频道，我有空会把视频发在里面。

**Comment by qssq** [comment]
https://t.me/qssq666  before url is error

**Comment by qssq** [comment]
https://hookui.lozn.top https://godhand.lozn.top
