### ISSUE TITLE
HookUI : lojun.autohookallclass , Documentation / Tutorial how to use.

### ISSUE THREAD

**Issue by Aryavrat0** [qssq/feedback#66]
Hello qssq ,
The application lojun.autohookallclass appears to be very good with lots of functions.But I am unable to make it work.

I am using Lsposed Framework for Xposed.
Is there any tutorial or documentation on how to use the application. I am aware that you have a QQ group , but due to overseas restrictions I am unable to join on QQ.Any tutorials / instructions on any other accessible platform like  GitHub or Telegram.

用谷歌翻译 : 

你好 qssq ，
 应用程序 lojun.autohookallclass 看起来非常好，有很多功能。但我无法让它工作。

 我正在为 Xposed 使用 Lsposed 框架。
 是否有任何关于如何使用该应用程序的教程或文档。 我知道您有一个 QQ 群，但由于海外限制，我无法加入 QQ。任何其他可访问平台（如 GitHub 或 Telegram）上的任何教程/说明。

**Comment by Dhruv420** [comment]
Same issue here , I can't join on QQ it won't let me create a account , any tutorial will be highly appreciated @qssq.

**Comment by qssq** [comment]
telegram @Dhruv420  @Aryavrat0  https://t.me/lojunX

**Comment by qssq** [comment]
twier is me private account ,sorry . @Aryavrat0 @Dhruv420  please you add my telegram account

**Comment by Aryavrat0** [comment]
> twier is me private account ,sorry . @Aryavrat0 @Dhruv420 please you add my telegram account

Thanks I've sent you a message on telegram :) . My telegram account is https://t.me/Aryavrat0

谢谢，我已经通过电报向您发送了一条消息:)。我的电报账户是 https://t.me/Aryavrat0
