### ISSUE TITLE
Unable to Hook Apps with no Storage permissions.

### ISSUE THREAD

**Issue by Aryavrat0** [qssq/feedback#67]
Hello qssq ,

With HOOKUI I am unable to hook apps that have no storage permission , the app freezes and terminal show this.

![Annotation 2021-07-22 210752](https://user-images.githubusercontent.com/87088283/126667284-cb7bba8d-bb60-4e6e-8989-e61fdd095ffe.png)

Even if I add storage permission in AndroidManifest.xml with the code below , I still get EACCES (Permission Denied) error

``` 
<uses-permission
         android:name="android.permission.WRITE_EXTERNAL_STORAGE"
         android:maxSdkVersion="Version code" />
```

![bhhh](https://user-images.githubusercontent.com/87088283/126668659-82c31341-9bd2-4841-afbc-108b079a0930.png)

**Comment by qssq** [comment]
是1.2版的hookui吗？不过已经默认开启了理论上问题不大，只要确保是组新版的hookui就行。

**Comment by qssq** [comment]
是1.2版的hookui吗？不过已经默认开启了理论上问题不大，只要确保是组新版的hookui就行。

**Comment by qssq** [comment]
https://t.me/qssq666 电报。

**Comment by qssq** [comment]
https://t.me/qssq666  before url is error

**Comment by qssq** [comment]
更新新版本
